[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "initialized_example.sw"
license = "Apache-2.0"
name = "initialized_src5_example"

[dependencies]
src_5 = { path = "../../../standards/src_5" }
