[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "multi_token_vault"

[dependencies]
src_6 = { path = "../../../standards/src_6" }
src_20 = { path = "../../../standards/src_20" }
