[workspace]
members = [
  "src3-mint-burn/single_asset",
  "src3-mint-burn/multi_asset",
  "src5-ownership/initialized_example",
  "src5-ownership/uninitialized_example",
  "src7-metadata/single_asset",
  "src7-metadata/multi_asset",
  "src20-token/single_asset",
  "src20-token/multi_asset",
]
