[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "multi_token_vault"

[dependencies]
src20 = { path = "../../../standards/src20-token" }
src6 = { path = "../../../standards/src6-vault" }
